services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: linux
      MYSQL_DATABASE: stock_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql_initialisation:/docker-entrypoint-initdb.d
    networks:
      - stockapp-network

  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://root:linux@db/stock_app
      FLASK_APP: flaskapp/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - stockapp-network

  ticker:
    build: ./backend
    container_name: stock_ticker
    command: /app/ticker.sh
    environment:
      DATABASE_HOST: db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - stockapp-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app            # frontend live reload
      - /app/node_modules          # prevent node_modules override
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - stockapp-network

volumes:
  mysql_data:

networks:
  stockapp-network:
    driver: bridge
